<section class="user-edit">
	<h2>Edit User</h2>
	
	<?php if ($this->error): ?>
		<p class="error">
			There were one or more issues with your submission.
			Please correct them as
			indicated below.
		</p>
	<?php endif ?>
	
	<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url(
		NULL,
		array('controller'=>'user-manager', 'action' => 'process')
	));
	$form->setAttribute('method', 'post');
	
	echo $this->form()->openTag($form);
	
	?>
	
	<dl class="zend_form">
		<dt><?php echo $this->formLabel($form->get('first_name')); ?></dt>
		<dd>
			<?php
			echo $this->formElement($form->get('id'));
			echo $this->formElement($form->get('first_name'));
			echo $this->formElementErrors($form->get('first_name'));
			?>
		</dd>
		<dt><?php echo $this->formLabel($form->get('last_name')); ?></dt>
		<dd>
			<?php
			echo $this->formElement($form->get('last_name'));
			echo $this->formElementErrors($form->get('last_name'));
			?>
		</dd>
		<dt><?php echo $this->formLabel($form->get('company_id')); ?></dt>
		<dd>
			<?php
			echo $this->formElement($form->get('company_id'));
			echo $this->formElementErrors($form->get('company_id'));
			?>
		</dd>
		<dt><?php echo $this->formLabel($form->get('group_id')); ?></dt>
		<dd>
			<?php
			echo $this->formElement($form->get('group_id'));
			echo $this->formElementErrors($form->get('group_id'));
			?>
		</dd>
		<dt>
			<?php echo $this->formLabel($form->get('email')); ?>
		</dt>
		<dd>
			<?php
			echo $this->formElement($form->get('email'));
			echo $this->formElementErrors($form->get('email'));
			?>
		</dd>
		<dt>
			<?php echo $this->formLabel($form->get('password'));?>
		</dt>
		<dd>
			<?php
			echo $this->formElement($form->get('password'));
			echo $this->formElementErrors($form->get('password'));
			?>
		</dd>
		<dt>
			<?php echo $this->formLabel($form->get('confirm_password')); ?>
		</dt>
		<dd>
			<?php
			echo $this->formElement($form->get('confirm_password'));
			echo $this->formElementErrors($form->get('confirm_password'));
			?>
		</dd>
		<dd>
			<?php
			echo $this->formElement($form->get('submit'));
			echo $this->formElementErrors($form->get('submit'));
			?>
		</dd>
	</dl>
<?php echo $this->form()->closeTag() ?>
</section>
