<h1>Users</h1>
<table class="table">
	<tr>
		<th>
			Name 
		</th>
		<th>
			Company
		</th>
		<th>
			Email:
		</th>
		<th>
			Group:
		</th>
		<th>
			Action:
		</th>
	</tr>
<?php
foreach ($users as $user) {
	?>
	<tr>
		<td>
			<?php echo $this->escapeHtml($user->first_name.' '.$user->last_name); ?>
		</td>
		<td>
			<?php echo $this->escapeHtml($user->name); ?>
		</td>
		<td>
			<?php echo $this->escapeHtml($user->email); ?>
		</td>
		<td>
			<?php echo $this->escapeHtml($user->group_name); ?>
		</td>
		<td>
			<a href="<?php echo $this->url('users/user-manager', array('action'=>'edit', 'id' => $user->id));?>">Edit</a> | <a href="<?php echo $this->url('users/user-manager', array('action'=>'delete', 'id' => $user->id));?>">Delete</a>
		</td>
	</tr>
	<?php
}
?>
</table>